### ISSUE TITLE
Change Hermaphrodite to Intersex

### ISSUE THREAD

**Issue by cameronmore** [johnbeve/STEMIO#2]
This is might be better placed in PATO, the Phenotype and Trait Ontology, but a more up-to-date term for hermaphrodite is intersex. Intersex refers to specifically human hermaphroditism, and it might serve our ontology if the term is changed, or if intersex is added as a subclass of hermaphrodite that describes specifically human cases of hermaphroditism.

**Comment by johnbeve** [comment]
This is better-suited for the PATO team; closing.
